version: '3.8'
services:
  els01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.1
    container_name: els01
    ports:
      - 9200:9200
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - node.name=els01
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=els01
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false 
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
        memlock:
          soft: -1
          hard: -1  
    networks:
     - elasticnetwork  
     

  kib01:
    image: docker.elastic.co/kibana/kibana:8.6.1
    container_name: kib01
    ports:
      - 5601:5601
    depends_on:
      - els01
    environment:
       ELASTICSEARCH_URL: http://els01:9200
       ELASTICSEARCH_HOSTS: http://els01:9200  
    networks:
      - elasticnetwork


volumes:
  elasticsearch-data:
    driver: local

networks:
  elasticnetwork:
    driver: bridge
    